### ISSUE TITLE
External module styles

### ISSUE THREAD

**Issue by dizlexik** [coox/styled-jsx-css-loader#1]
I can't get this to work with external style imports, e.g.:
```js
import styles from 'some-lib/some-stylesheet.css';
```

**Comment by coox** [comment]
Hello @dizlexik —

The loader should work no matter where the CSS file comes from, as long as it is resolved properly, which in your case would simply imply `some-lib` to be an installed dependency, exposing the `some-stylesheet.css` file.

The reason I think this could fail is a Babel setup interference between your environment (which I presume runs babel-loader right after styled-jsx-css-loader) and the `some-lib` dependency.

Could you please post the specific error that you are encountering, as well as the relevant sections of your webpack and Babel configs, and the actual name of the external package you want to import from (assuming it’s published on npm)?

**Comment by coox** [comment]
Hello @dizlexik —

Are you still experiencing this issue with version 0.3.0?

If so, it would help if you could please post the specifics mentioned above. I’ll be happy to help.

**Comment by dizlexik** [comment]
It has been quite a journey to try to get this thing working, but still no luck. First issue was that the library I'm trying to include a CSS file from has a .babelrc file in it so I found that I need to add `babelrc: false` to my babel-loader options. Then I was getting an error that `styled-jsx/css doesn't exist` so I found that I need to include `presets: ['next/babel']` in my babel-loader options. Finally I have it building successfully, but still not working. A CSS file is now being output into my dist directory that looks like what I want but the component that I'm trying to import it into is trying to load in the original CSS file from the library in node_modules and throwing an error because it's not valid JS. Shouldn't the import be loading the generated file instead?

**Comment by coox** [comment]
Thanks for the details of your journey so far, @dizlexik. Indeed, the steps you have taken appear to resolve commonly encountered issues, and we’ve updated the configuration guide to hopefully solve this (see [README](https://github.com/coox/styled-jsx-css-loader/blob/master/README.md)).

I can think of two things that might cause the error you are still facing:

- modules might not be transformed properly, because next/babel defaults babel-preset-env’s module configuration to `false` — try to use `{ "preset-env": { "modules": "commonjs" } }` in your next/babel options
- are you explicitly using `node_modules` in the path of your imports? that could explain why Next.js (or Node) attempts to load your module from there instead of the build directory. your imports should use a path relative to the resolved module, for example `import buttonStyle from 'semantic-ui-css/components/button.css'` (borrowed from #3)

**Comment by dizlexik** [comment]
Updating my next/babel preset options as you specified made no difference. It still appears to be loading the CSS as-is and I'm getting the same error as before: `SyntaxError: Unexpected token .` (because the first character in the CSS file is a dot)

No I'm not using node_modules in the path. I'm importing with the format `import styles from 'the-lib/the-styles.css'`

**Comment by TilBlechschmidt** [comment]
I just attempted to do exactly what @dizlexik posted in the op.
```javascript
import styles from 'some-node-module/lib/plugin.css';

...
() => (
    <style jsx global>
        {styles}
    </style>
)
```

it gives me this error:
```
Error while running `getDataFromTree` ReferenceError: styles is not defined
```

But when I take the `styles` variable and write it into a temporary variable (inside the render method) and use that in the style tag it works.

**Comment by ghost** [comment]
Hi @coox first of all, thank you for this great plugin. 

I have a problem when using the global prop. I'm trying to include bulma as sass, it's sort of working without the global prop, but I want the import to be global, unscoped. 

```
// styles/styles.css
@import "node_modules/bulma/bulma.sass";

body {
  background-color: #1a1a1a;
}
```

```javascript
import React from "react"
import Head from "next/head"
import mainStyles from "styles/styles.scss"
import normalizeCss from "styles/normalize.css"

export default props => (
  <div className="container">
    <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>

    {props.children}

    <style jsx global>{mainStyles}</style>
    <style jsx>{normalizeCss}</style>
  </div>
)

```

Using the global prop as shown above, I get the following error: 

```bash
mainStyles is not defined
ReferenceError: mainStyles is not defined
    at _default (Components/Layout/index.jsx:7:0)
    at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:13381:0)
    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:13821:0)
    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:15864:0)
    at workLoop (node_modules/react-dom/cjs/react-dom.development.js:15903:0)
    at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:15943:0)
    at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:16561:0)
    at performWork (node_modules/react-dom/cjs/react-dom.development.js:16483:0)
    at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:16455:0)
    at requestWork (node_modules/react-dom/cjs/react-dom.development.js:16355:0)
```

And if I don't use it, my global style gets scoped. 

<img width="552" alt="screen shot 2018-08-30 at 8 50 04 pm" src="https://user-images.githubusercontent.com/4138205/44888351-50795180-ac96-11e8-9bc3-903c9836741f.png">
<img width="1337" alt="screen shot 2018-08-30 at 8 49 13 pm" src="https://user-images.githubusercontent.com/4138205/44888352-50795180-ac96-11e8-911a-839011e46243.png">

Is there any way around this ? 

@TheMegaTB solution works, but it's way too hacky. 

Thanks 👍

**Comment by stphnnnn** [comment]
I'm getting the same after upgrading to Next.js 6.1.1

**Comment by coox** [comment]
Closing all issues as I am archiving this project, which I will no longer maintain. 👋️
